### ISSUE TITLE
Automate new user welcoming and onboarding

### ISSUE THREAD

**Issue by aassoiants** [Bitcoin-Product-Community/bitcoin-product-community#15]
**User story**
- As a new user joining Discord, I want a smooth onboarding experience where I feel welcome and certain of next steps

Refer [here](https://miro.com/app/board/uXjVPktFKLM=/?moveToWidget=3458764547651091684&cot=14) for M2 Onboarding journey map.

DONE **V1 Requirements**
- Mods are notified when there is a new member
- Mods manually send out a greeting and welcome

DONE **V2 Requirements**
- Bot sends out greeting and welcome

**V3 Requirements** 
- Bot sends welcome message and intro docs to consume

**Comment by Dimi8146** [comment]
Completed as desired. For historical record, the message is as follows:

`Hi {user},
Thanks for joining the {server}! 

Our vision is to create a space for product-oriented bitcoiners to collaborate and positively impact the bitcoin ecosystem. We’re excited you’ve joined us and can’t wait to meet you.

But first, please take a few minutes to go through the following articles to better understand what our group is about:

[BPC Orientation video](https://www.youtube.com/watch?v=Lr58-sNJlZo)
[We are the Bitcoin Product Community blog](https://bitcoinproduct.substack.com/p/we-are-the-bitcoin-product-community)
[As a Product Manager you are…a janitor, essentially](https://medium.com/all-things-product-management/product-manager-you-are-664d83ee702e)

Once you’re done, introduce yourself in the [intro channel](https://discord.com/channels/988346170701135902/1082351175413800971) so we can get to know you!

Then check out the various discord channels we have. For example, explore our latest updates in [announcements](https://discord.com/channels/988346170701135902/1060721304854077560), find job or volunteer posts in [opportunities](https://discord.com/channels/988346170701135902/989165003473043536), get a quick laugh in [memes](https://discord.com/channels/988346170701135902/1081607476203495487), and find a group to level up your skills with in [learning-club](https://discord.com/channels/988346170701135902/1080631404284608532).

Finally, subscribe to our [newsletter](https://bitcoinproduct.substack.com/about) and calendar ([iCAL](https://calendar.google.com/calendar/ical/bitcoinpms%40gmail.com/public/basic.ics) , [Google Calendar](https://calendar.google.com/calendar/u/4?cid=Yml0Y29pbnBtc0BnbWFpbC5jb20) ) to stay up to date!
`
